<div class="title">Aplicaciones de Análisis &ndash; TensorFlow</div>
<div class="subtitle">Máster en Big Data y Data Science</div>
<div class="author">Carlos María Alaíz Gudín - Universidad Autónoma de Madrid</div>

---

**Configuración inicial**

In [1]:
%%html
<head><link rel="stylesheet" href="style.css"></head>

In [2]:
%load_ext tensorboard

import numpy as np

import matplotlib
import matplotlib.pyplot as plt

import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

from tensorflow.python.util import deprecation
deprecation._PRINT_DEPRECATION_WARNINGS = False

import tensorflow as tf
gpu_devices = tf.config.experimental.list_physical_devices("GPU")
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)

matplotlib.rc("figure", figsize=(15, 5))

seed = 1234

/home/daniel/anaconda3/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


# Introducción

## ¿Qué es TensorFlow?

* TensorFlow es una librería/framwork *open source* desarrollada por Google para computación numérica usando el flujo de datos en un grafo.
Lógicamente, tiene un uso muy adecuado para el desarrollo de modelos de Aprendizaje Automático (*Machine Learning*, ML).
* Desarrollada inicialmente como proyecto interno (Google Brain y Google's Machine Intelligence Research), su implementación de código abierto fue liberada en noviembre de 2015 (bajo licencia Apache 2.0).
* Su primera  versión estable fue publicada en noviembre de 2018.
* La versión estable actual es la 2.10.

## La importancia de TensorFlow

### Impacto

* Flexible y escalable.
* Utilizada tanto en entornos de investigación como en sistemas productivos.
* Hay grandes compañías que lo están utilizando actualmente:

<img src="figures/Companies_using_TF.png" width="100%">

### Funcionalidad como herramienta de *Deep Learning*

* TensorFlow es una herramienta muy completa para *Deep Learning*, como muestra la siguiente tabla comparativa (extraída de [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_deep-learning_software)):

<table class="wikitable sortable" style="text-align: center; font-size: 50%; width: 100%; table-layout: fixed;">

<tbody><tr>
<th style="width: 12em">Software
</th>
<th>Creator
</th>
<th>Initial release
</th>
<th>Software license<sup id="cite_ref-license_1-0" class="reference"><a href="#cite_note-license-1">&#91;a&#93;</a></sup>
</th>
<th>Open source
</th>
<th>Platform
</th>
<th>Written in
</th>
<th>Interface
</th>
<th><a href="/wiki/OpenMP" title="OpenMP">OpenMP</a> support
</th>
<th><a href="/wiki/OpenCL" title="OpenCL">OpenCL</a> support
</th>
<th><a href="/wiki/CUDA" title="CUDA">CUDA</a> support
</th>
<th><a href="/wiki/Automatic_differentiation" title="Automatic differentiation">Automatic differentiation</a><sup id="cite_ref-2" class="reference"><a href="#cite_note-2">&#91;1&#93;</a></sup>
</th>
<th>Has pretrained models
</th>
<th><a href="/wiki/Recurrent_neural_network" title="Recurrent neural network">Recurrent nets</a>
</th>
<th><a href="/wiki/Convolutional_neural_network" title="Convolutional neural network">Convolutional nets</a>
</th>
<th><a href="/wiki/Restricted_Boltzmann_machine" title="Restricted Boltzmann machine">RBM</a>/<a href="/wiki/Deep_belief_network" title="Deep belief network">DBNs</a>
</th>
<th>Parallel execution (multi node)
</th>
<th>Actively developed
</th></tr>
<tr>
<td><a href="/wiki/BigDL" title="BigDL">BigDL</a>
</td>
<td>Jason Dai (Intel)
</td>
<td>2016
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_License" title="Apache License">Apache 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>Apache Spark
</td>
<td>Scala
</td>
<td>Scala, Python
</td>
<td>
</td>
<td>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td>
<td>
</td>
<td>
</td></tr>
<tr>
<td><a href="/wiki/Caffe_(software)" title="Caffe (software)">Caffe</a>
</td>
<td>Berkeley Vision and Learning Center
</td>
<td>2013
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/BSD_licenses" title="BSD licenses">BSD</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a><sup id="cite_ref-3" class="reference"><a href="#cite_note-3">&#91;2&#93;</a></sup>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/MATLAB" title="MATLAB">MATLAB</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Under development<sup id="cite_ref-4" class="reference"><a href="#cite_note-4">&#91;3&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-5" class="reference"><a href="#cite_note-5">&#91;4&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background: #ececec; color: #2C2C2C; font-size: smaller; vertical-align: middle; text-align: center;" class="unknown table-unknown">?
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No<sup id="cite_ref-6" class="reference"><a href="#cite_note-6">&#91;5&#93;</a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Chainer" title="Chainer">Chainer</a>
</td>
<td>Preferred Networks
</td>
<td>2015
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/BSD_licenses" title="BSD licenses">BSD</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No<sup id="cite_ref-7" class="reference"><a href="#cite_note-7">&#91;6&#93;</a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Deeplearning4j" title="Deeplearning4j">Deeplearning4j</a>
</td>
<td>Skymind engineering team; Deeplearning4j community; originally Adam Gibson
</td>
<td>2014
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_2.0" class="mw-redirect" title="Apache 2.0">Apache 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>, <a href="/wiki/Android_(operating_system)" title="Android (operating system)">Android</a> (<a href="/wiki/Cross-platform" class="mw-redirect" title="Cross-platform">Cross-platform</a>)
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a>
</td>
<td><a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a>, <a href="/wiki/Scala_(programming_language)" title="Scala (programming language)">Scala</a>, <a href="/wiki/Clojure_(programming_language)" class="mw-redirect" title="Clojure (programming language)">Clojure</a>, <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a> (<a href="/wiki/Keras" title="Keras">Keras</a>), <a href="/wiki/Kotlin_(programming_language)" title="Kotlin (programming language)">Kotlin</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No<sup id="cite_ref-8" class="reference"><a href="#cite_note-8">&#91;7&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-9" class="reference"><a href="#cite_note-9">&#91;8&#93;</a></sup><sup id="cite_ref-10" class="reference"><a href="#cite_note-10">&#91;9&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Computational Graph
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-11" class="reference"><a href="#cite_note-11">&#91;10&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-12" class="reference"><a href="#cite_note-12">&#91;11&#93;</a></sup>
</td>
<td>Yes
</td></tr>
<tr>
<td><a href="/wiki/Dlib" title="Dlib">Dlib</a>
</td>
<td>Davis King
</td>
<td>2002
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Boost_Software_License" class="mw-redirect" title="Boost Software License">Boost Software License</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Cross-platform" class="mw-redirect" title="Cross-platform">Cross-platform</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td></tr>
<tr>
<td><a href="/wiki/Flux_(machine-learning_framework)" title="Flux (machine-learning framework)">Flux</a>
</td>
<td>Mike Innes
</td>
<td>2017
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/MIT_license" class="mw-redirect" title="MIT license">MIT license</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">MacOS</a>, <a href="/wiki/Windows" class="mw-redirect" title="Windows">Windows</a> (<a href="/wiki/Cross-platform_software" title="Cross-platform software">Cross-platform</a>)
</td>
<td><a href="/wiki/Julia_(programming_language)" title="Julia (programming language)">Julia</a>
</td>
<td><a href="/wiki/Julia_(programming_language)" title="Julia (programming language)">Julia</a>
</td>
<td>
</td>
<td>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-13" class="reference"><a href="#cite_note-13">&#91;12&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td>Intel <a href="/wiki/Data_Analytics_Acceleration_Library" title="Data Analytics Acceleration Library">Data Analytics Acceleration Library</a>
</td>
<td>Intel
</td>
<td>2015
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_License_2.0" class="mw-redirect" title="Apache License 2.0">Apache License 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a> on <a href="/wiki/Intel" title="Intel">Intel</a> <a href="/wiki/Central_processing_unit" title="Central processing unit">CPU</a><sup id="cite_ref-intel-daal_14-0" class="reference"><a href="#cite_note-intel-daal-14">&#91;13&#93;</a></sup>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a><sup id="cite_ref-intel-daal_14-1" class="reference"><a href="#cite_note-intel-daal-14">&#91;13&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td></tr>
<tr>
<td>Intel <a href="/wiki/Math_Kernel_Library" title="Math Kernel Library">Math Kernel Library</a>
</td>
<td>Intel
</td>
<td>
</td>
<td style="background: #ddf; vertical-align: middle; text-align: center;" class="table-proprietary"><a href="/wiki/Proprietary_software" title="Proprietary software">Proprietary</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a> on <a href="/wiki/Intel" title="Intel">Intel</a> <a href="/wiki/Central_processing_unit" title="Central processing unit">CPU</a><sup id="cite_ref-15" class="reference"><a href="#cite_note-15">&#91;14&#93;</a></sup>
</td>
<td>
</td>
<td><a href="/wiki/C_(programming_language)" title="C (programming language)">C</a><sup id="cite_ref-16" class="reference"><a href="#cite_note-16">&#91;15&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-17" class="reference"><a href="#cite_note-17">&#91;16&#93;</a></sup>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-intel-benchmark_18-0" class="reference"><a href="#cite_note-intel-benchmark-18">&#91;17&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-intel-benchmark_18-1" class="reference"><a href="#cite_note-intel-benchmark-18">&#91;17&#93;</a></sup>
</td>
<td>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td>
</td></tr>
<tr>
<td><a href="/wiki/Keras" title="Keras">Keras</a>
</td>
<td>François Chollet
</td>
<td>2015
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/MIT_license" class="mw-redirect" title="MIT license">MIT license</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/R_(programming_language)" title="R (programming language)">R</a>
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Only if using Theano as backend
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Can use Theano, Tensorflow or PlaidML as backends
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-19" class="reference"><a href="#cite_note-19">&#91;18&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No<sup id="cite_ref-20" class="reference"><a href="#cite_note-20">&#91;19&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-21" class="reference"><a href="#cite_note-21">&#91;20&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/MATLAB" title="MATLAB">MATLAB</a> + Deep Learning Toolbox
</td>
<td><a href="/wiki/MathWorks" title="MathWorks">MathWorks</a>
</td>
<td>
</td>
<td style="background: #ddf; vertical-align: middle; text-align: center;" class="table-proprietary"><a href="/wiki/Proprietary_software" title="Proprietary software">Proprietary</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>
</td>
<td><a href="/wiki/C_(programming_language)" title="C (programming language)">C</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a>, <a href="/wiki/MATLAB" title="MATLAB">MATLAB</a>
</td>
<td><a href="/wiki/MATLAB" title="MATLAB">MATLAB</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Train with Parallel Computing Toolbox and generate CUDA code with GPU Coder<sup id="cite_ref-22" class="reference"><a href="#cite_note-22">&#91;21&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-23" class="reference"><a href="#cite_note-23">&#91;22&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-NNT_24-0" class="reference"><a href="#cite_note-NNT-24">&#91;23&#93;</a></sup><sup id="cite_ref-25" class="reference"><a href="#cite_note-25">&#91;24&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-NNT_24-1" class="reference"><a href="#cite_note-NNT-24">&#91;23&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-NNT_24-2" class="reference"><a href="#cite_note-NNT-24">&#91;23&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">With Parallel Computing Toolbox<sup id="cite_ref-26" class="reference"><a href="#cite_note-26">&#91;25&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/Microsoft_Cognitive_Toolkit" title="Microsoft Cognitive Toolkit">Microsoft Cognitive Toolkit</a> (CNTK)
</td>
<td><a href="/wiki/Microsoft_Research" title="Microsoft Research">Microsoft Research</a>
</td>
<td>2016
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/MIT_license" class="mw-redirect" title="MIT license">MIT license</a><sup id="cite_ref-27" class="reference"><a href="#cite_note-27">&#91;26&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>, <a href="/wiki/Linux" title="Linux">Linux</a><sup id="cite_ref-Setup_CNTK_on_your_machine_28-0" class="reference"><a href="#cite_note-Setup_CNTK_on_your_machine-28">&#91;27&#93;</a></sup> (<a href="/wiki/MacOS" title="MacOS">macOS</a> via Docker on roadmap)
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a> (<a href="/wiki/Keras" title="Keras">Keras</a>), <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Command_line" class="mw-redirect" title="Command line">Command line</a>,<sup id="cite_ref-29" class="reference"><a href="#cite_note-29">&#91;28&#93;</a></sup> BrainScript<sup id="cite_ref-30" class="reference"><a href="#cite_note-30">&#91;29&#93;</a></sup> (<a href="/wiki/.NET_Framework" title=".NET Framework">.NET</a> on roadmap<sup id="cite_ref-31" class="reference"><a href="#cite_note-31">&#91;30&#93;</a></sup>)
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-32" class="reference"><a href="#cite_note-32">&#91;31&#93;</a></sup>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-33" class="reference"><a href="#cite_note-33">&#91;32&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-cntk.ai_34-0" class="reference"><a href="#cite_note-cntk.ai-34">&#91;33&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-cntk.ai_34-1" class="reference"><a href="#cite_note-cntk.ai-34">&#91;33&#93;</a></sup>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No<sup id="cite_ref-35" class="reference"><a href="#cite_note-35">&#91;34&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-36" class="reference"><a href="#cite_note-36">&#91;35&#93;</a></sup>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No<sup id="cite_ref-37" class="reference"><a href="#cite_note-37">&#91;36&#93;</a></sup>
</td></tr>
<tr>
<td>Apache <a href="/wiki/MXNet" class="mw-redirect" title="MXNet">MXNet</a>
</td>
<td>Apache Software Foundation
</td>
<td>2015
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_2.0" class="mw-redirect" title="Apache 2.0">Apache 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>,<sup id="cite_ref-38" class="reference"><a href="#cite_note-38">&#91;37&#93;</a></sup><sup id="cite_ref-39" class="reference"><a href="#cite_note-39">&#91;38&#93;</a></sup> <a href="/wiki/Amazon_Web_Services" title="Amazon Web Services">AWS</a>, <a href="/wiki/Android_(operating_system)" title="Android (operating system)">Android</a>,<sup id="cite_ref-40" class="reference"><a href="#cite_note-40">&#91;39&#93;</a></sup> <a href="/wiki/IOS" title="IOS">iOS</a>, <a href="/wiki/File_manager" title="File manager">JavaScript</a><sup id="cite_ref-41" class="reference"><a href="#cite_note-41">&#91;40&#93;</a></sup>
</td>
<td>Small <a href="/wiki/C%2B%2B" title="C++">C++</a> core library
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/Julia_(programming_language)" title="Julia (programming language)">Julia</a>, <a href="/wiki/Matlab" class="mw-redirect" title="Matlab">Matlab</a>, <a href="/wiki/JavaScript" title="JavaScript">JavaScript</a>, <a href="/wiki/Go_(programming_language)" title="Go (programming language)">Go</a>, <a href="/wiki/R_(programming_language)" title="R (programming language)">R</a>, <a href="/wiki/Scala_(programming_language)" title="Scala (programming language)">Scala</a>, <a href="/wiki/Perl_(programming_language)" class="mw-redirect" title="Perl (programming language)">Perl</a>, <a href="/wiki/Clojure_(programming_language)" class="mw-redirect" title="Clojure (programming language)">Clojure</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">On roadmap<sup id="cite_ref-42" class="reference"><a href="#cite_note-42">&#91;41&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-43" class="reference"><a href="#cite_note-43">&#91;42&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-44" class="reference"><a href="#cite_note-44">&#91;43&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-45" class="reference"><a href="#cite_note-45">&#91;44&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/Neural_Designer" title="Neural Designer">Neural Designer</a>
</td>
<td>Artelnics
</td>
<td>2014
</td>
<td style="background: #ddf; vertical-align: middle; text-align: center;" class="table-proprietary"><a href="/wiki/Proprietary_software" title="Proprietary software">Proprietary</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td><a href="/wiki/Graphical_user_interface" title="Graphical user interface">Graphical user interface</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">Analytical differentiation
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/OpenNN" title="OpenNN">OpenNN</a>
</td>
<td>Artelnics
</td>
<td>2003
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/GNU_Lesser_General_Public_License" title="GNU Lesser General Public License">GNU LGPL</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Cross-platform" class="mw-redirect" title="Cross-platform">Cross-platform</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #ececec; color: #2C2C2C; font-size: smaller; vertical-align: middle; text-align: center;" class="unknown table-unknown">?
</td>
<td style="background: #ececec; color: #2C2C2C; font-size: smaller; vertical-align: middle; text-align: center;" class="unknown table-unknown">?
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background: #ececec; color: #2C2C2C; font-size: smaller; vertical-align: middle; text-align: center;" class="unknown table-unknown">?
</td>
<td>
</td></tr>
<tr>
<td><a href="/wiki/PlaidML" title="PlaidML">PlaidML</a>
</td>
<td><a href="/w/index.php?title=Vertex.AI&amp;action=edit&amp;redlink=1" class="new" title="Vertex.AI (page does not exist)">Vertex.AI</a>, <a href="/wiki/Intel" title="Intel">Intel</a>
</td>
<td>2017
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_2.0" class="mw-redirect" title="Apache 2.0">Apache 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Windows" class="mw-redirect" title="Windows">Windows</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/OpenCL" title="OpenCL">OpenCL</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td style="background: #ececec; color: #2C2C2C; font-size: smaller; vertical-align: middle; text-align: center;" class="unknown table-unknown">?
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Some OpenCL ICDs are not recognized
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/PyTorch" title="PyTorch">PyTorch</a>
</td>
<td>Adam Paszke, Sam Gross, Soumith Chintala, Gregory Chanan (Facebook)
</td>
<td>2016
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/BSD_licenses" title="BSD licenses">BSD</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Windows" class="mw-redirect" title="Windows">Windows</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/C_(programming_language)" title="C (programming language)">C</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/CUDA" title="CUDA">CUDA</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Julia_(programming_language)" title="Julia (programming language)">Julia</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Via separately maintained package<sup id="cite_ref-46" class="reference"><a href="#cite_note-46">&#91;45&#93;</a></sup><sup id="cite_ref-auto_47-0" class="reference"><a href="#cite_note-auto-47">&#91;46&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a rel="nofollow" class="external text" href="https://github.com/zhongkaifu/Seq2SeqSharp">Seq2SeqSharp</a>
</td>
<td>Zhongkai Fu
</td>
<td>2018
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/BSD_licenses" title="BSD licenses">BSD</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Windows" class="mw-redirect" title="Windows">Windows</a>
</td>
<td><a href="/wiki/C%EF%BC%83_(programming_language)" class="mw-redirect" title="C＃ (programming language)">C#</a>, <a href="/wiki/C_(programming_language)" title="C (programming language)">C</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/CUDA" title="CUDA">CUDA</a>
</td>
<td><a href="/wiki/C%EF%BC%83_(programming_language)" class="mw-redirect" title="C＃ (programming language)">C#</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/Apache_SINGA" title="Apache SINGA">Apache SINGA</a>
</td>
<td><a href="/wiki/Apache_Software_Foundation" class="mw-redirect" title="Apache Software Foundation">Apache Software Foundation</a>
</td>
<td>2015
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_2.0" class="mw-redirect" title="Apache 2.0">Apache 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Supported in V1.0
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #ececec; color: #2C2C2C; font-size: smaller; vertical-align: middle; text-align: center;" class="unknown table-unknown">?
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td>
</td></tr>
<tr>
<td><a href="/wiki/TensorFlow" title="TensorFlow"><mark>TensorFlow</mark></a>
</td>
<td><a href="/wiki/Google_Brain" title="Google Brain">Google Brain</a>
</td>
<td>2015
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/Apache_2.0" class="mw-redirect" title="Apache 2.0">Apache 2.0</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>,<sup id="cite_ref-TensorFlow.org_48-0" class="reference"><a href="#cite_note-TensorFlow.org-48">&#91;47&#93;</a></sup><sup id="cite_ref-developers.googleblog.com_49-0" class="reference"><a href="#cite_note-developers.googleblog.com-49">&#91;48&#93;</a></sup> <a href="/wiki/Android_(operating_system)" title="Android (operating system)">Android</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>, <a href="/wiki/CUDA" title="CUDA">CUDA</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a> (<a href="/wiki/Keras" title="Keras">Keras</a>), <a href="/wiki/C_(programming_language)" title="C (programming language)">C</a>/<a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Java_(programming_language)" title="Java (programming language)">Java</a>, <a href="/wiki/Go_(programming_language)" title="Go (programming language)">Go</a>, <a href="/wiki/JavaScript" title="JavaScript">JavaScript</a>, <a href="/wiki/R_(programming_language)" title="R (programming language)">R</a>,<sup id="cite_ref-50" class="reference"><a href="#cite_note-50">&#91;49&#93;</a></sup> <a href="/wiki/Julia_(programming_language)" title="Julia (programming language)">Julia</a>, <a href="/wiki/Swift_(programming_language)" title="Swift (programming language)">Swift</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">On roadmap<sup id="cite_ref-tensorflow-roadmap_51-0" class="reference"><a href="#cite_note-tensorflow-roadmap-51">&#91;50&#93;</a></sup> but already with <a href="/wiki/SYCL" title="SYCL">SYCL</a><sup id="cite_ref-GitHub_52-0" class="reference"><a href="#cite_note-GitHub-52">&#91;51&#93;</a></sup> support
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-tensorflow.org_53-0" class="reference"><a href="#cite_note-tensorflow.org-53">&#91;52&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-github.com_54-0" class="reference"><a href="#cite_note-github.com-54">&#91;53&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<td><a href="/wiki/Theano_(software)" title="Theano (software)">Theano</a>
</td>
<td><a href="/wiki/Universit%C3%A9_de_Montr%C3%A9al" title="Université de Montréal">Université de Montréal</a>
</td>
<td>2007
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/BSD_licenses" title="BSD licenses">BSD</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Cross-platform" class="mw-redirect" title="Cross-platform">Cross-platform</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a>
</td>
<td><a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python</a> (<a href="/wiki/Keras" title="Keras">Keras</a>)
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Under development<sup id="cite_ref-55" class="reference"><a href="#cite_note-55">&#91;54&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-56" class="reference"><a href="#cite_note-56">&#91;55&#93;</a></sup><sup id="cite_ref-57" class="reference"><a href="#cite_note-57">&#91;56&#93;</a></sup>
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Through Lasagne's model zoo<sup id="cite_ref-58" class="reference"><a href="#cite_note-58">&#91;57&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-59" class="reference"><a href="#cite_note-59">&#91;58&#93;</a></sup>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td></tr>
<tr>
<td><a href="/wiki/Torch_(machine_learning)" title="Torch (machine learning)">Torch</a>
</td>
<td>Ronan Collobert, Koray Kavukcuoglu, Clement Farabet
</td>
<td>2002
</td>
<td style="background: #ddfd; color: black; vertical-align: middle; text-align: center;" class="free table-free"><a href="/wiki/BSD_licenses" title="BSD licenses">BSD</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td><a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>,<sup id="cite_ref-auto1_60-0" class="reference"><a href="#cite_note-auto1-60">&#91;59&#93;</a></sup> <a href="/wiki/Android_(operating_system)" title="Android (operating system)">Android</a>,<sup id="cite_ref-61" class="reference"><a href="#cite_note-61">&#91;60&#93;</a></sup> <a href="/wiki/IOS" title="IOS">iOS</a>
</td>
<td><a href="/wiki/C_(programming_language)" title="C (programming language)">C</a>, <a href="/wiki/Lua_(programming_language)" title="Lua (programming language)">Lua</a>
</td>
<td><a href="/wiki/Lua_(programming_language)" title="Lua (programming language)">Lua</a>, <a href="/wiki/Lua_(programming_language)" title="Lua (programming language)">LuaJIT</a>,<sup id="cite_ref-62" class="reference"><a href="#cite_note-62">&#91;61&#93;</a></sup> <a href="/wiki/C_(programming_language)" title="C (programming language)">C</a>, utility library for <a href="/wiki/C%2B%2B" title="C++">C++</a>/<a href="/wiki/OpenCL" title="OpenCL">OpenCL</a><sup id="cite_ref-jtorch_63-0" class="reference"><a href="#cite_note-jtorch-63">&#91;62&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background: #FED; color: black; vertical-align: middle; text-align: center;" class="depends table-depends">Third party implementations<sup id="cite_ref-64" class="reference"><a href="#cite_note-64">&#91;63&#93;</a></sup><sup id="cite_ref-65" class="reference"><a href="#cite_note-65">&#91;64&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-66" class="reference"><a href="#cite_note-66">&#91;65&#93;</a></sup><sup id="cite_ref-67" class="reference"><a href="#cite_note-67">&#91;66&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Through <a href="/wiki/Twitter" title="Twitter">Twitter</a>'s Autograd<sup id="cite_ref-68" class="reference"><a href="#cite_note-68">&#91;67&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-69" class="reference"><a href="#cite_note-69">&#91;68&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-auto1_60-1" class="reference"><a href="#cite_note-auto1-60">&#91;59&#93;</a></sup>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td></tr>
<tr>
<td><a href="/wiki/Wolfram_Mathematica" title="Wolfram Mathematica">Wolfram Mathematica</a>
</td>
<td><a href="/wiki/Wolfram_Research" title="Wolfram Research">Wolfram Research</a>
</td>
<td>1988
</td>
<td style="background: #ddf; vertical-align: middle; text-align: center;" class="table-proprietary"><a href="/wiki/Proprietary_software" title="Proprietary software">Proprietary</a>
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td><a href="/wiki/Microsoft_Windows" title="Microsoft Windows">Windows</a>, <a href="/wiki/MacOS" title="MacOS">macOS</a>, <a href="/wiki/Linux" title="Linux">Linux</a>, <a href="/wiki/Cloud_computing" title="Cloud computing">Cloud computing</a>
</td>
<td><a href="/wiki/C%2B%2B" title="C++">C++</a>, <a href="/wiki/Wolfram_Language" title="Wolfram Language">Wolfram Language</a>, <a href="/wiki/CUDA" title="CUDA">CUDA</a>
</td>
<td><a href="/wiki/Wolfram_Language" title="Wolfram Language">Wolfram Language</a>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#F99;vertical-align:middle;text-align:center;" class="table-no">No
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-70" class="reference"><a href="#cite_note-70">&#91;69&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes<sup id="cite_ref-71" class="reference"><a href="#cite_note-71">&#91;70&#93;</a></sup>
</td>
<td style="background:#9F9;vertical-align:middle;text-align:center;" class="table-yes">Yes
</td></tr>
<tr>
<th style="width: 12em">Software
</th>
<th>Creator
</th>
<th>Initial release
</th>
<th>Software license<sup id="cite_ref-license_1-1" class="reference"><a href="#cite_note-license-1">&#91;a&#93;</a></sup>
</th>
<th>Open source
</th>
<th>Platform
</th>
<th>Written in
</th>
<th>Interface
</th>
<th><a href="/wiki/OpenMP" title="OpenMP">OpenMP</a> support
</th>
<th><a href="/wiki/OpenCL" title="OpenCL">OpenCL</a> support
</th>
<th><a href="/wiki/CUDA" title="CUDA">CUDA</a> support
</th>
<th><a href="/wiki/Automatic_differentiation" title="Automatic differentiation">Automatic differentiation</a><sup id="cite_ref-72" class="reference"><a href="#cite_note-72">&#91;71&#93;</a></sup>
</th>
<th>Has pretrained models
</th>
<th><a href="/wiki/Recurrent_neural_network" title="Recurrent neural network">Recurrent nets</a>
</th>
<th><a href="/wiki/Convolutional_neural_network" title="Convolutional neural network">Convolutional nets</a>
</th>
<th><a href="/wiki/Restricted_Boltzmann_machine" title="Restricted Boltzmann machine">RBM</a>/<a href="/wiki/Deep_belief_network" title="Deep belief network">DBNs</a>
</th>
<th>Parallel execution (multi node)
</th>
<th>Actively developed
</th></tr></tbody></table>

## El ecosistema TensorFlow

* **Tensorflow**: Librería principal del ecosistema, diseñada para desarrollar y entrenar modelos de ML en Python.
* **TensorFlow.js**: Librería JavaScript para entrenar y desplegar modelos en el navegador y en Node.js.
* **TensorFlow Lite**: Librería ligera para desplegar modelos en móviles y dispositivos embebidos.
* **TensorFlow Extended (TFX)**: Plataforma *end-to-end* para preprocesar los datos, entrenar, validar y desplegar modelos en grandes entornos de producción.

# Primeros pasos

## Infraestructura

* Instalar TensorFlow (y Keras), o...
* Usar [Google Colab](https://colab.research.google.com/).

In [3]:
import tensorflow as tf

print("Versión de TensorFlow disponible:", tf.__version__)

Versión de TensorFlow disponible: 2.8.0


## Tensores

* Los tensores son arrays multidimensionales de un cierto tipo de dato, similares a los `ndarrays` de NumPy.
<img src="figures/Tensor.png" width="400" alt="Tensor de 4 dimensiones.">

### Creación de tensores

* Se pueden crear fácilmente los tensores a partir de listas y arrays de NumPy.

In [4]:
print("Rank 0 tensor:", tf.constant(4))
print("Rank 1 tensor:", tf.constant([1., 3., 4.]))
print("Rank 4 tensor:", tf.constant(np.arange(120).reshape(3, 2, 4, 5)))

Rank 0 tensor: tf.Tensor(4, shape=(), dtype=int32)
Rank 1 tensor: tf.Tensor([1. 3. 4.], shape=(3,), dtype=float32)
Rank 4 tensor: tf.Tensor(
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]]


 [[[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]

  [[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]]


 [[[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]], shape=(3, 2, 4, 5), dtype=int64)


* Los tensores se pueden convertir fácilmente en arrays de NumPy (por ejemplo, para imprimirlos o pintarlos).

In [5]:
tensor = tf.random.normal([3])

print("Tensor: ", tensor)
print("Ndarray:", tensor.numpy())

Tensor:  tf.Tensor([-0.0332428 -1.3646157  0.8283514], shape=(3,), dtype=float32)
Ndarray: [-0.0332428 -1.3646157  0.8283514]


<div class="qst">

* Crear un tensor aleatorio (con `tf.random.normal`) de nombre `dataset`, que represente un conjunto de datos de $10$ vídeos, cada uno de los cuales estará compuesto por $4$ *frames* de tamaño $3 \times 2$.
* ¿Cuántos píxeles hay en total en el conjunto de datos?
* ¿Cuál sería la dimensión de entrada de un modelo de ML que clasificara estos vídeos?

</div>

In [ ]:
dataset = None

################################
# Insertar código.
dataset = tf.random.normal((10, 4, 3, 2))
print("No. pixels:   ", np.prod(dataset.shape))
print("No. features: ", np.prod(dataset.shape[1:]))
################################

### Operaciones con tensores

* Se pueden realizar operaciones entre tensores, y con escalares, igual que en NumPy.

In [ ]:
tensor_1 = tf.constant([[1., 2], [3, 4]])
tensor_2 = tf.ones([2, 2])

print("Sum:", tensor_1 + tensor_2)
print("\nProduct:", tensor_1 * tensor_2)
print("\nMatrix product:", tensor_1 @ tensor_2)
print("\nScalar product:", 10 * tensor_2)

* También se pueden realizar operaciones a lo largo de los tensores.

In [ ]:
print("Mean:    ", tf.reduce_mean(tensor_1).numpy())
print("Mean Ax0:", tf.reduce_mean(tensor_1, axis=0).numpy())
print("Mean Ax1:", tf.reduce_mean(tensor_1, axis=1).numpy())
print("Max:     ", tf.reduce_max(tensor_1).numpy())
print("Min:     ", tf.reduce_min(tensor_1).numpy())
print("ArgSort: ", tf.argsort(tensor_1).numpy())

<div class="qst">

* Calcular la media de cada *frame* de cada vídeo del conjunto `dataset` creado anteriormente, e imprimirla por pantalla.
* Obtener la suma de los 4 *frames* que componen cada vídeo de `dataset`, e imprimirla por pantalla.

<div class="notes">

* El parámetro `axis` puede recibir una lista de ejes a lo largo de los que realizar una operación.

</div>

</div>

In [ ]:
################################
# Insertar código.
print("Averages of frames:")
print(tf.reduce_mean(dataset, axis=[2, 3]).numpy())

print("\nSum of frames:")
print(tf.reduce_sum(dataset, axis=[1]).numpy())
################################

### Forma de los tensores

* Hay diversas utilidades para extraer información acerca de la forma y composición de los tensores.

In [ ]:
tensor = tf.constant([["a", "b", "c"], ["d", "e", "f"]])

print("Type:          ", tensor.dtype)
print("No. Dimensions:", tensor.ndim)
print("Shape:         ", tensor.shape)
print("No. elements:  ", tf.size(tensor).numpy())

* Se pueden realizar modificaciones sobre la forma de los tensores.

In [ ]:
print(tf.reshape(tensor, [3, 2]), "\n")
print(tf.reshape(tensor, [-1]))

<div class="qst">

* Crear una modificación del conjunto `dataset` donde cada patrón (cada vídeo) sea un vector, en lugar de un tensor de dimensión $3$.
* ¿Qué sentido puede tener esta transformación de los datos?

</div>

In [ ]:
################################
# Insertar código.
print("Converted dataset:")
print(tf.reshape(dataset, [dataset.shape[0], -1]).numpy())
################################

### Indexado

* El indexado es similar al de NumPy.

In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(tensor[:].numpy(), "\n")
print(tensor[1:, :].numpy(), "\n")
print(tensor[1, 2].numpy(), "\n")
print(tensor[:, ::2].numpy(), "\n")

<div class="qst">

* Seleccionar, del conjunto `dataset`, el segundo *frame* del tercer vídeo.
* Seleccionar el tercer *frame* de los primeros $5$ vídeos.

</div>

In [ ]:
################################
# Insertar código.
print("Video 3, Frame 2:")
print(dataset[2, 1].numpy())

print("\nVideos 1-5, Frame 3:")
print(dataset[:5, 2].numpy())
################################

### Inmutabilidad

* Todos los tensores son inmutables.
* En lugar de modificarlos, hay que crear tensores nuevos.

In [ ]:
tensor_1 = tf.ones((3, 2))
print("Tensor at the beginning:", tensor_1)

try:
    tensor_1[1, 0] = 2
except:
    print("\nException raised!\n")
finally:
    print("Tensor at the end:", tensor_1)

<div class="qst">

* Crear un tensor a partir de `dataset`, donde el tercer *frame* de cada vídeo se haya puesto todo a $0$.

<div class="notes">

 * En ocasiones, puede ser útil transformar los tensores en arrays de NumPy para modificarlos.

</div>
</div>

In [ ]:
################################
# Insertar código.
array = dataset.numpy()
array[:, 2, :, :] = 0
print(tf.constant(array))
################################

### Expansión

* El *broadcasting* es similar al de NumPy.

In [ ]:
print(tf.ones([3, 4]) + tf.constant([1, 2, 3, 4], dtype=tf.float32), "\n")
print(tf.ones([3, 4]) + tf.reshape(tf.constant([1, 2, 3], dtype=tf.float32), [-1, 1]))

<div class="qst">

* Crear un tensor a partir de `dataset` donde se sume $1$ a cada *frame* del primer vídeo, $2$ a cada *frame* del segundo, y así sucesivamente.

</div>

In [ ]:
################################
# Insertar código.
print(tf.reshape(tf.range(1, 11, dtype=tf.float32), [-1, 1, 1, 1]) + dataset)
################################

<div class="info"><a href="https://www.tensorflow.org/guide/tensor">Tensores</a></div>

## *Eager Execution* vs. *Graph Execution*

* TensorFlow provee dos tipos distintos de ejecución, *Eager Execution* (EE) y *Graph Execution* (GE).

### TensorFlow EE

* En TensorFlow, se conoce como EE la ejecución de forma inmediata de las operaciones.
* A partir de la versión 2.0 se convirtió en la opción por defecto.
* Este tipo de ejecución es más "pytónica", ya que:
    * Presenta una interfaz más intuitiva, con código Python natural.
    * Es más fácil de depurar, ya que se ven los resultados directamente.
    * Permite usar el control de flujo de Python.
    * Soporta también aceleración GPU y TPU.

### TensorFlow GE

* GE se apoya en en la construcción de grafos donde se definirán los cálculos a realizar que, posteriormente, se evaluarán (diagrama de flujos de datos).
* Como en cualquier grafo, hay nodos y aristas.
    * Las aristas son los tensores (los datos).
    * Los nodos representan las operaciones a realizar.
    * Los resultados de unas operaciones se pueden utilizar como entradas para las siguientes.
* Esta representación presenta varia ventajas:
    * Los grafos se pueden guardar, cargar, exportar, etc., sin el código Python original.
    * Los grafos pueden ser optimizados, ya que se conoce de antemano todo el proceso que se va a hacer.
    * Los grafos pueden dividirse en subgrafos independientes.
    * Es más fácil distribuir la carga de trabajo de manera no trivial.
* Aunque actualmente la ejecución por defecto es EE, se puede forzar GE usando las funciones de TensorFlow.
    * Se pueden crear los modelos usando EE, y luego optimizarlos para predecir con GE.

* La extensión TensorBoard permite mostrar los grafos de una función en modo GE.

In [6]:
from datetime import datetime

@tf.function
def example_func(x, y, z):
    a = tf.add(y, x, name="Add")
    b = tf.multiply(a, z, name="Mul1")
    c = tf.multiply(z, b, name="Mul2")
    return b, c

logdir = "logs/func/" + datetime.now().strftime("%Y%m%d-%H%M%S")
writer = tf.summary.create_file_writer(logdir)

# Input data.
x = tf.constant(10)
y = tf.constant(20)
z = tf.constant(30)

tf.summary.trace_on(graph=True, profiler=True)
r = example_func(x, y, z)
with writer.as_default():
    tf.summary.trace_export(
        name="example_func_trace",
        step=0,
        profiler_outdir=logdir)

%tensorboard --logdir logs/func

### Comparativa

| Entorno *Eager Execution*       | Entorno *Graph Execution*               |
|:--------------------------------|:----------------------------------------|
| Fácil de depurar.               | Rápido y flexible.                      |
| Intuitivo.                      | Ejecución en paralelo.                  |
| Fácil para construir prototipos.| Muy eficiente, múltiples dispositivos.  |
| Amigable para principiantes.    | Aceleración GPU y TPU más potente.      |

In [ ]:
import timeit

def function_eager(x):
    return tf.reduce_sum(x) + 2 * x - x * tf.nn.relu(x ** 2) + 3 * tf.reduce_mean(x) * tf.reduce_sum(x)
function_graph = tf.function(function_eager)

tensor = tf.constant(np.arange(100000))

print("Eager:", function_eager(tensor).numpy()[:3])
print("Graph:", function_graph(tensor).numpy()[:3])

In [ ]:
print("Eager time: %.4fs" % timeit.timeit(lambda: function_eager(tensor), number=1000))
print("Graph time: %.4fs" % timeit.timeit(lambda: function_graph(tensor), number=1000))

<div class="qst">

* Crear una función de nombre `mean_add` que tome dos tensores, calcule la media del primero, y se lo sume al segundo. La función deberá ejecutarse en modo GE.

</div>

In [ ]:
################################
# Insertar código.
def mean_add(x, y):
    return tf.reduce_mean(x) + y
mean_add = tf.function(mean_add)
################################

logdir = "logs/mean_add/" + datetime.now().strftime("%Y%m%d-%H%M%S")
writer = tf.summary.create_file_writer(logdir)

x = tf.random.normal((3, 2))
y = tf.ones((2, 4, 5))

tf.summary.trace_on(graph=True, profiler=True)
z = mean_add(x, y)
with writer.as_default():
    tf.summary.trace_export(
        name="example_mean_add_trace",
        step=0,
        profiler_outdir=logdir)

%tensorboard --logdir logs/mean_add

<div class="info"><a href="https://www.tensorflow.org/guide/intro_to_graphs">Introducción a grafos y funciones</a></div>

## Variables

* Una variable de TensorFlow representa un tensor cuyo valor puede cambiar realizando operaciones sobre él.
* Es la forma estándar de representar los parámetros de un modelo, que se modificarán durante el entrenamiento.

### Creación de variables

In [ ]:
print("Rank 0 variable:", tf.Variable(4))
print("Rank 1 variable:", tf.Variable([1., 3., 4.]))
print("Rank 4 variable:", tf.Variable(np.arange(120).reshape(3, 2, 4, 5)))

* Al igual que con los tensores, las variables se convierten fácilmente en arrays.

In [ ]:
tensor = tf.random.normal([3])
variable = tf.Variable(tensor)

print("Variable: ", variable)
print("Ndarray:", variable.numpy())

### Formas y operaciones con variables

* Como las variables están construidas sobre tensores, comparten muchos atributos y la mayor parte de las operaciones

In [ ]:
print("Type:        ", variable.dtype)
print("Shape:       ", variable.shape)
print("No. elements:", tf.size(variable).numpy())

In [ ]:
print("Variable:", variable)
print("Tensor:  ", tf.convert_to_tensor(variable))
print("ArgMax:  ", tf.argmax(variable).numpy())

* Si se intenta modificar la forma de una variable, lo que se obtiene es un tensor copia de la variable con la nueva forma.

In [ ]:
print("Reshape:", tf.reshape(variable, ([1, 3])))

* Se puede cambiar el contenido del tensor donde la variable guarda los datos, y la memoria en principio se reutilizará.
* El tipo de variable y sus dimensiones se mantendrán constantes.

In [ ]:
print(variable)
variable.assign([1, 2, 3])
print(variable)

try:
    variable.assign([1, 2, 3, 4])
except Exception as e:
    print("Exception:", e)

* Si se crea una variable a partir de otra, se copiará y las dos serán independientes.

In [ ]:
variable_2 = tf.Variable(variable)
variable_2.assign([4, 5, 6])

print("variable:  ", variable)
print("variable_2:", variable_2)

* Las operaciones tensoriales convierten las variables en tensores.

In [ ]:
print("Tensor:  ", variable + 2)
print("Variable:", variable.assign_add([2, 2, 2]))

<div class="qst">

* Crear dos variables escalares, `w` y `b`, para representar los parámetros de un modelo lineal de una variable.
* Crear una función `linear_model` que reciba tres argumentos, `x` (un vector), `w` y `b`, y que calcule la salida del modelo lineal para cada elemento de `x`.

</div>

In [ ]:
################################
# Insertar código.
w = tf.Variable(0.0)
b = tf.Variable(0.0)

def linear_model(x, w, b):
    return x * w + b
################################

x = tf.cast(tf.linspace(-1, 1, 101), dtype=tf.float32)

plt.plot(x.numpy(), linear_model(x, w, b).numpy(), '*')
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.show()

<div class="info"><a href="https://www.tensorflow.org/guide/variable">Variables</a></div>

# Diferenciación automática

## Cálculo de gradientes

* Una de las grandes herramientas de TensorFlow es la diferenciación automática.
* Para poder realizarla, TensorFlow necesita registrar las operaciones y su orden de ejecución durante la fase *forward*.
* Durante la fase *backward*, las operaciones se recorren en sentido contrario para calcular los gradientes.
* Para realizar este registro de operaciones se utilizan las cintas de gradiente (Gradient Tapes, GT).
* Por tanto, el cálculo que se desee diferenciar deberá realizarse en el contexto de una GT, que se usará después para calcular el gradiente.

A continuación se muestra un ejemplo muy sencillo, en el que se diferencia la función
$$ f(x) = x^2 + 3 x - 2 \implies f'(x) = 2x + 3 ,$$
en el punto $x = 3$.

In [ ]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2 + 3 * x - 2

print("Tape:", tape)

In [ ]:
print("f'(3) =", tape.gradient(y, x).numpy())

En el siguiente ejemplo, el gradiente se calcula para todo un vector.
En este caso, como `x` es un tensor, y no una variable, se especifica explícitamente que la GT lo registre.

In [ ]:
x = tf.linspace(-2, 2, 101)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y = x**2 + x
    z = tf.nn.sigmoid(y)

dzx = tape.gradient(z, x)
dzy = tape.gradient(z, y)
dyx = tape.gradient(y, x)

In [ ]:
plt.plot(x.numpy(), y.numpy(), label="$y$")
plt.plot(x.numpy(), z.numpy(), label="$z$")
plt.plot(x.numpy(), dyx.numpy(), label="$\\partial y/\partial x$")
plt.plot(x.numpy(), dzx.numpy(), label="$\\partial z/\partial x$")
plt.plot(x.numpy(), dzy.numpy(), label="$\\partial z/\partial y$")

plt.legend()
plt.xlabel('$x$')
plt.show()

<div class="qst">

* Dados los vectores `x_tr` e `y_tr`, calcular las derivadas respecto a `w` y `b` del error cuadrático (calculado con la función `tf.metrics.mean_squared_error`) del modelo lineal definido anteriormente.
* Comprobar si coincide esta derivada con el resultado teórico:
\begin{align*}
\frac{\partial}{\partial w} \|\mathbf{x} w + b - y\|^2 &= \frac{2}{N} \mathbf{x}^\intercal (\mathbf{x} w + b - y) ; \\
\frac{\partial}{\partial b} \|\mathbf{x} w + b - y\|^2 &= \frac{2}{N} \sum_i (x_i w + b - y_i) .
\end{align*}

</div>

In [ ]:
x_tr = tf.cast(tf.linspace(-1, 1, 101), dtype=tf.float32)
y_tr = x_tr * 2 + 5

################################
# Insertar código.
with tf.GradientTape(persistent=True) as tape:
    y_pr = linear_model(x_tr, w, b)
    e = tf.metrics.mean_squared_error(y_tr, y_pr)

dew = tape.gradient(e, w)
deb = tape.gradient(e, b)
print("dew (auto.):", dew.numpy())
print("deb (auto.):", deb.numpy())
################################

print("dew (theor.):", (2 * tf.tensordot(x_tr, x_tr * w + b - y_tr, 1) / len(x_tr)).numpy())
print("deb (theor.):", (2 * tf.reduce_sum(x_tr * w + b - y_tr) / len(x_tr)).numpy())

## Optimización con TensorFlow

* La principal utilidad del cálculo de gradientes es resolver problemas de optimización.
* Aunque Keras proporciona un marco mucho más cómodo para hacer esto, usando TensorFlow se puede afrontar el problema de manera manual.

En la siguiente celda se muestra un problema de optimización en dos variables.

In [ ]:
def objective(x1, x2): 
    return (x1 - 3.0)**2.0 - 3 * x1  + (2.0 * x2 + 4.0)**2.0 + 1e-2 * x1**2 * x2

v = np.linspace(-10, 10, 101)
v1, v2 = np.meshgrid(v, v)
v3 = objective(v1, v2)

plt.figure(figsize=(10, 10))
plt.pcolor(v1, v2, v3, shading="auto")
plt.axis([-10, 10, -10, 10])
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")

plt.show()

A continuación se resuelve el problema de minimización mediante descenso por gradiente.

In [ ]:
x1 = tf.Variable(-9.0)
x2 = tf.Variable(+9.0)

# Learning rate.
eta = 1e-1

evo = [[x1.numpy(), x2.numpy()]]
for i in range(50):
    with tf.GradientTape() as tape:
        f = objective(x1, x2)
    grads = tape.gradient(f, [x1, x2])
    x1.assign(x1 - eta * grads[0].numpy())
    x2.assign(x2 - eta * grads[1].numpy())
    evo.append([x1.numpy(), x2.numpy()])

evo = np.array(evo)

In [ ]:
plt.figure(figsize=(10, 10))
plt.pcolor(v1, v2, v3, shading="auto")
plt.axis([-10, 10, -10, 10])
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")

plt.plot(evo[:, 0], evo[:, 1], '-*w')

plt.show()

<div class="qst">

* Entrenar el modelo lineal dado por `w` y `b` sobre el conjunto de datos (`x_tr`, `y_tr`) del ejercicio anterior.
* Comprobar si el resultado obtenido se corresponde con el modelo subyacente.

</div>

In [ ]:
################################
# Insertar código.
for i in range(100):
    with tf.GradientTape(persistent=True) as tape:
        y_pr = linear_model(x_tr, w, b)
        e = tf.metrics.mean_squared_error(y_tr, y_pr)

    dew = tape.gradient(e, w)
    deb = tape.gradient(e, b)
    w.assign_add(- eta * dew)
    b.assign_add(- eta * deb)
################################

print("w_opt:", w.numpy())
print("b_opt:", b.numpy())

plt.plot(x_tr.numpy(), y_tr.numpy(), '*', label="Observed")
plt.plot(x_tr.numpy(), linear_model(x_tr, w, b).numpy(), "-", label="Model")
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.legend()
plt.show()

<div class="info"><a href="https://www.tensorflow.org/guide/autodiff">Diferenciación automática</a></div>